config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  root 'dashboards#index'
  mount Sidekiq::Web => '/sidekiq'
  mount ActionCable.server => '/cable'

  namespace :admin do
    resource :sessions, only: %i[new create]
    resource :settings, only: %i[show update]
    resource :synchronizes, only: %i[create]
    resource :restore_services, only: %i[create]

    resources :registrar_users, param: :uuid
    resources :domain_prices, param: :uuid, except: %i[show]

    namespace :contacts do
      resource :searches, only: %i[show]
    end
  end

  resource :sessions, only: %i[new]
  delete 'logout', to: 'sessions#destroy'

  namespace :settings do
    resources :configurations, only: %i[index create]
    resources :introduces, only: %i[index]

    namespace :est_tld do
      resource :validations, only: %i[create]
    end
  end

  namespace :auth do
    match '/tara/setup', via: %i[get post], to: 'tara#setup'
    match '/tara/callback', via: %i[get post], to: 'tara#callback', as: :tara_callback
    match '/tara/cancel', via: %i[get post delete], to: 'tara#cancel',
                          as: :tara_cancel
    get '/failure', to: 'tara#cancel'
  end

  namespace :registrar do
    resources :poll_messages, only: %i[update index] do
      scope module: :poll_messages do
        resource :dequeues, only: %i[update]
      end
    end
    resources :invoices, param: :uuid
    resources :contacts, param: :uuid do
      collection do
        get :search
      end
    end
    resources :domains, param: :uuid
    resources :renews, param: :uuid, only: %i[show update]
    resource :sessions, only: %i[new create destroy]
    resource :transfers, only: %i[show update]
    resource :settings, only: %i[show update]
  end

  namespace :registrant do
    resources :domains, param: :uuid
    resource :profiles, only: %i[edit update]
    resources :pending_actions, param: :uuid, only: %i[show]

    resources :contacts, param: :uuid do
      collection do
        get :search
      end
    end

    scope module: :invoices do
      resource :pay_invoices, only: %i[create]
      match '/pay_invoices_callback', via: %i[get], to: 'pay_invoices#callback', as: :pay_invoices_callback
    end
  end
end

app/models/contact/est_tld/country.rb
module Contact::EstTld::Country
  extend ActiveSupport::Concern

  included do
    validate :validate_country_code
    validate :validate_address_country_code
  end

  private

  def validate_country_code
    if country_code.present? && !ISO3166::Country[country_code]
      errors.add(:country_code, 'должен быть действительным кодом страны в формате alpha2')
    end
  end

  def validate_address_country_code
    if address_country_code.present? && !ISO3166::Country[address_country_code]
      errors.add(:address_country_code, 'должен быть действительным кодом страны в формате alpha2')
    end
  end
end

app/models/contact/est_tld/legal_doc.rb
module Contact::EstTld::LegalDoc
  extend ActiveSupport::Concern

  included do
    has_one_attached :legal_document
  end
end

app/models/contact/est_tld/roles.rb
module Contact::EstTld::Roles
  extend ActiveSupport::Concern

  included do
    enum role: { priv: 100, org: 200 }
  end
end

app/controllers/admin/contacts/searches_controller.rb
module Admin
  module Contacts
    class SearchesController < ApplicationController
      include Roles::AdminAbilitable

      def show
        puts '----'
        puts params[:query]
        puts '-----'

        @contacts = Contact.search(params[:query])

        puts '==== contacts'
        puts @contacts.inspect
        puts '====='

        render json: @contacts.limit(5).map(&:as_json)
      end
    end
  end
end

app/controllers/registrant/contacts_controller.rb
module Registrant
  class ContactsController < ApplicationController
    include Roles::RegistrantAbilitable

    def new
      @contact = Contact.new
    end

    def create
    end

    def search
      @contacts = Contact.where('ident ILIKE ?', "%#{params[:query]}%")

      render json: @contacts.limit(5).map(&:as_json)
    end
  end
end

app/controllers/registrar/contacts_controller.rb
module Registrar
  class ContactsController < ApplicationController
    include Roles::RegistrarAbilitable

    before_action :load_contact, only: %i[edit update destroy show]

    def index
      @pagy, @contacts = pagy(Contact.search_filter(params).distinct, items: 15, link_extra: 'data-turbo-action="advance"')
    end

    def new
      @contact = Contact.new
    end

    def show; end

    def create
      @contact = Contact.new(contact_params)

      if @contact.save
        redirect_to registrar_contacts_path, status: :see_other, notice: t('.success')
      else
        flash[:alert] = @contact.errors.full_messages.join(', ')
        render 'registrar/contacts/new', status: :unprocessable_entity
      end
    end

    def update
      if @contact.update(contact_params)
        redirect_to registrar_contacts_path, status: :see_other, notice: t('.success')
      else
        flash[:alert] = @contact.errors.full_messages.join(', ')
        render 'registrar/contacts/edit', status: :unprocessable_entity
      end
    end

    def destroy
      if @contact.destroy
        redirect_to registrar_contacts_path, status: :see_other, notice: t('.success')
      else
        Rails.logger.info @contact.errors.inspect
        flash[:alert] = @contact.errors.full_messages.join(', ')
        render 'registrar/contacts/index', status: :unprocessable_entity
      end
    end

    def search
      puts '----'
      puts params[:query]
      puts '-----'

      @contacts = Contact.search(params[:query])

      puts '==== contacts'
      puts @contacts.inspect
      puts '====='

      render json: @contacts.limit(5).map(&:as_json)
    end

    private

    def load_contact
      @contact = Contact.find_by(uuid: params[:uuid])
    end

    def contact_params
      params.require(:contact).permit(:code, :country_code, :ident, :phone_code,
                                      :role, :name, :email, :phone, :address_country_code,
                                      :city, :street, :state, :zip, :legal_document)
    end
  end
end

app/controllers/registrar/domains_controller.rb
module Registrar
  class DomainsController < ApplicationController
    include Roles::RegistrarAbilitable

    before_action :load_domain, only: %i[show edit update destroy]

    def index
      @pagy, @domains = pagy(Domain.search(params).distinct, items: 15, link_extra: 'data-turbo-action="advance"')
    end

    def new
      @domain = Domain.new
      Tld::Estonian::MIN_NAMESERVER_COUNT.times do
        @domain.nameservers.build
      end
      Tld::Estonian::MIN_DOMAIN_CONTACT_COUNT.times do |i|
        i % 2 == 0 ? @domain.domain_contacts.build(type: 'AdminDomainContact') : @domain.domain_contacts.build(type: 'TechDomainContact')
      end

      @domain.dnssec_keys.build
    end

    def create
      domain_params_modified = domain_params.except(:period)
      @domain = Domain.new(domain_params_modified)
      period = params[:domain][:period].to_i
      @domain.expire_at = calculate_expiry(period)

      if @domain.save
        redirect_to registrar_domains_path, status: :see_other, notice: t('.success')
      else
        Rails.logger.info @domain.errors.inspect
        flash[:alert] = @domain.errors.full_messages.join(', ')
        render :new, status: :unprocessable_entity
      end
    end

    def show; end

    def edit; end

    def update
      domain_params_modified = domain_params.except(:period)
      period = params[:domain][:period].to_i
      domain_params_modified[:expire_at] = calculate_expiry(period)

      if @domain.update(domain_params_modified)
        redirect_to registrar_domains_path, status: :see_other, notice: t('.success')
      else
        Rails.logger.info @domain.errors.inspect
        flash[:alert] = @domain.errors.full_messages.join(', ')
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      if @domain.destroy
        redirect_to registrar_domains_path, status: :see_other, notice: t('.success')
      else
        Rails.logger.info @domain.errors.inspect
        flash[:alert] = @domain.errors.full_messages.join(', ')
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def load_domain
      @domain = Domain.find_by(uuid: params[:uuid])
    end

    def calculate_expiry(period)
      (Time.zone.now.advance(months: period) + 1.day).beginning_of_day
    end

    def domain_params
      params.require(:domain).permit(:name, :registrant_id, :period, :reserved_pw,
                                     domain_contacts_attributes: %i[id contact_id type _destroy],
                                     nameservers_attributes: %i[id hostname ipv4 ipv6 _destroy],
                                     dnssec_keys_attributes: %i[id flags protocol algorithm public_key _destroy])
    end
  end
end

app/controllers/registrar/invoices_controller.rb
module Registrar
  class InvoicesController < ApplicationController
    include Roles::RegistrarAbilitable

    before_action :load_invoice, only: %i[show edit update destroy]

    def index
      @pagy, @invoices = pagy(Invoice.all.order(created_at: :desc), items: 15, link_extra: 'data-turbo-action="advance"')
    end

    def show; end

    def new
      @invoice = Invoice.new
      @invoice.invoice_items.build
    end

    def create
      @invoice = Invoice.new(invoice_params)

      if @invoice.save
        redirect_to registrar_invoices_path, status: :see_other, notice: t('.success')
      else
        Rails.logger.info @invoice.errors.inspect
        flash[:alert] = @invoice.errors.full_messages.join(', ')
        render :new, status: :unprocessable_entity
      end
    end

    def edit; end

    def update
      if @invoice.update(invoice_params)
        redirect_to registrar_invoices_path, status: :see_other, notice: t('.success')
      else
        Rails.logger.info @invoice.errors.inspect
        flash[:alert] = @invoice.errors.full_messages.join(', ')
        render :edit, status: :unprocessable_entit
      end
    end

    def destroy
      if @invoice.destroy
        redirect_to registrar_invoices_path, status: :see_other, notice: t('.success')
      else
        Rails.logger.info @invoice.errors.inspect
        flash[:alert] = @invoice.errors.full_messages.join(', ')
        render :index, status: :unprocessable_entit
      end
    end

    private

    def load_invoice
      @invoice = Invoice.find_by(uuid: params[:uuid])
    end

    def invoice_params
      params.require(:invoice).permit(:buyer_id, :name, :country_code, :state, :street, :city, :zip, :phone, :url, :status,
                                      :email, :description, :invoice_items_attributes => [:id, :unit_price, :quantity, :description, :_destroy] )
    end
  end
end

app/controllers/registrar/poll_messages/dequeues_controller.rb
module Registrar
  module PollMessages
    class DequeuesController < ApplicationController
      # rubocop:disable Metrics/AbcSize
      # rubocop:disable Metrics/MethodLength
      def update
        result = EstonianTld::PollMessageService.new(tld:).mark_as_read(params[:poll_message_id])

        if result.success

          data = EstonianTld::SummaryService.call(tld: @tld)
          struct_data = EstonianTld::SummarySerializer.call(dirty: data)
          @notification = struct_data[:notification]
          @notifications_count = struct_data[:notifications_count]

          flash.now[:notice] = t('.success')
          render turbo_stream: [
            turbo_stream.append('flash', partial: 'layouts/flash'),

            # TODO: This is not working. Need to fix animation playing before execute another turbo actions.
            # turbo_stream.poll_message_dequeue('message-box', element_id: 'message-box'),

            turbo_stream.update('notification-header',
                                html: "#{t('dashboards.notifications.notification_title')} (#{@notifications_count})"),
            if @notification
              turbo_stream.append('dashboard-notification', partial: 'dashboards/notifications/message',
                                                            locals: { notification: @notification })
            else
              turbo_stream.append('dashboard-notification', partial: 'dashboards/notifications/no_message')
            end
          ]
        else
          flash[:alert] = t('.failure')
          render turbo_stream: [
            turbo_stream.append('flash', partial: 'layouts/flash')
          ]
        end
      end
    end
  end
end

app/controllers/registrar/poll_messages_controller.rb
module Registrar
  class PollMessagesController < ApplicationController
    include Roles::RegistrarAbilitable
    before_action :notifications

    def index; end

    # rubocop:disable Metrics/AbcSize
    # rubocop:disable Metrics/MethodLength
    def update
      result = EstonianTld::PollMessageService.new(tld:).mark_as_read(params[:id])

      if result.success
        flash.now[:notice] = t('.success')
        render turbo_stream: [
          turbo_stream.append('flash', partial: 'layouts/flash'),
          turbo_stream.poll_message_mark_as_read("poll_message_#{params[:id]}", item_id: params[:id]),
          turbo_stream.append('poll_messages', partial: 'registrar/poll_messages/poll_message',
                                               locals: { poll_message: @poll_messages.last })
        ]
      else
        flash[:alert] = t('.failure')
        render turbo_stream: [
          turbo_stream.append('flash', partial: 'layouts/flash')
        ]
        # render 'dashboards/index', status: :unprocessable_entity
      end
    end

    def notifications
      all_notifications = EstonianTld::PollMessageService.new(tld: @tld).all_notifications

      puts '----'
      puts all_notifications.body['data']
      puts '----'

      @all_notifications = if all_notifications.body['data'].blank?
                             []
                           else
                             EstonianTld::NotificationSerializer.call(body: all_notifications.body['data'])
                           end

      @pagy, @poll_messages = pagy_array(@all_notifications, items: 15, link_extra: 'data-turbo-action="advance"')
    end
  end
end

app/controllers/registrar/renews_controller.rb
module Registrar
  class RenewsController < ApplicationController
    include Roles::RegistrarAbilitable

    def show
      @domain = Domain.find_by_uuid(params[:uuid])
    end

    # rubocop:disable Metrics/AbcSize
    # rubocop:disable Metrics/MethodLength
    def update
      @domain = Domain.find_by_uuid(params[:uuid])

      result = EstonianTld::RenewService.new(tld: Tld.first).transfer(
        payload: renew_params, domain_name: @domain.name
      )

      if result.success
        @domain.renew(period_in_months: renew_params[:period].to_i)
        redirect_to registrar_domains_path, notice: t('.success'), status: :see_other
      else
        Rails.logger.info "Error: #{result.body['message']}"
        flash.now[:alert] = "Error: #{result.body['message']}"

        render turbo_stream: turbo_stream.replace('flash', partial: 'layouts/flash')
      end
    end

    private

    def renew_params
      params.require(:domain).permit(:name, :period, :expire_at)
    end
  end
end

app/controllers/registrar/sessions_controller.rb
module Registrar
  class SessionsController < ApplicationController
    layout 'sessions'

    allow_unauthenticated only: %i[new create]

    def new
      redirect_to root_path if logged_in?
    end

    def create
      registrar_user = RegistrarUser.find_by(username: params[:username])

      if registrar_user&.authenticate(params[:password])
        app_token = registrar_user.app_sessions.create
        log_in app_token
        redirect_to root_path, status: :see_other, notice: { success: t('.success') }
      else
        render 'registrar/sessions/new', status: :unprocessable_entity
      end
    end

    def destroy
      logout

      flash[:success] = t('.success')
      redirect_to new_sessions_path, status: :see_other
    end
  end
end

app/controllers/registrar/settings_controller.rb
module Registrar
  class SettingsController < ApplicationController
    include Roles::RegistrarAbilitable

    def show
      @registrar_group = Setting.with_group('registrar')
    end

    def update
      if Setting.update(casted_settings.keys, casted_settings.values)
        redirect_to root_path, status: :see_other, notice: t('.success')
      else
        flash[:alert] = update.errors.values.uniq.join(', ')
        render :show, status: :unprocessable_entity
      end

      puts '----'
      puts casted_settings
      puts '----'
    end

    private

    def casted_settings
      settings = {}

      params[:settings].each do |k, v|
        settings[k] = { value: v }
      end

      settings
    end
  end
end

app/controllers/registrar/transfers_controller.rb
module Registrar
  class TransfersController < ApplicationController
    include Roles::RegistrarAbilitable

    def show; end

    def update
      result = EstonianTld::TransferService.new(tld: Tld.first).transfer(payload: transfer_params)

      if result.success
        redirect_to registrar_domains_path, notice: t('.success'), status: :see_other
      else
        Rails.logger.info "Error: #{result.body['message']}"
        render :show, alert: "Error: #{result.body['message']}", status: :unprocessable_entity
      end
    end

    def transfer_params
      params.require(:domain).permit(:domain_name, :transfer_code)
    end
  end
end

app/helpers/registrars/contacts_helper.rb
module Registrars
  module ContactsHelper
    def show_address?
      Setting.show_address_customer
    end
  end
end

app/views/registrar/contacts/_contact.html.erb
<tr>
  <td class="w-full max-w-0 py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:w-auto sm:max-w-none sm:pl-6">
    <%= contact.name %>
    <dl class="font-normal lg:hidden">
      <dt class="sr-only"><%= contact.name %></dt>
      <dd class="mt-1 truncate text-gray-700"><%= contact.code %></dd>
      <dt class="sr-only sm:hidden"><%= contact.email %></dt>
      <dd class="mt-1 truncate text-gray-500 sm:hidden"><%= contact.domains.pluck(:name).join(', ') %></dd>
    </dl>
  </td>
  <td class="hidden px-3 py-4 text-sm text-gray-500 lg:table-cell"><%= contact.code %></td>
  <td class="hidden px-3 py-4 text-sm text-gray-500 sm:table-cell"><%= contact.email %></td>
  <td class="hidden px-3 py-4 text-sm text-gray-500 sm:table-cell">
    <span class="py-1 px-4 rounded-3xl text-white <%= contact.active? ? 'bg-green-500' : 'bg-gray-500' %>"><%= contact.state %></span>
  </td>
  <td class="px-3 py-4 text-sm text-gray-500"><%= contact.domains.pluck(:name).join(', ') %></td>
  <td class="py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6 flex justify-end space-x-3">
    <%= link_to t('.show'), registrar_contact_path(uuid: contact.uuid), class: "px-3 py-1 rounded-md text-white bg-yellow-400 hover:bg-yellow-500 cursor-pointer", target: '_top' %>

    <%= link_to t('.edit'), edit_registrar_contact_path(uuid: contact.uuid), class: "px-3 py-1 rounded-md text-white bg-blue-400 hover:bg-blue-500 cursor-pointer", target: '_top' %>

    <%= button_to t('.delete'), registrar_contact_path(uuid: contact.uuid), method: :delete, class: "px-3 py-1 rounded-md text-white bg-red-400 hover:bg-red-500 cursor-pointer", form: { data: { turbo_confirm: t(".confirm_delete") } } %>
  </td>
</tr>

app/views/registrar/contacts/_filter.html.erb
<%= form_with url: registrar_contacts_path, method: :get, 
  data: { 
    controller: 'behaviour--togglable behaviour--debounce filter--clear-form', 
    behaviour__togglable_props_class: 'hidden', behaviour__debounce_target: 'form',
    filter__clear_form_target: 'form', turbo_action: 'advance',
    turbo_frame: 'contacts', action: 'input->behaviour--debounce#search' 
  } do |f| %>

  <div class='mt-4 flex justify-between items-center'>
    <%= component 'form/search_input', form: f, attr: :name, placeholder: t('.search_by_name'), label_name: t('.search_by_name_label'), options: { parent_css: 'w-96' } %>

    <div>
      <a class='text-md text-indigo-500 underline cursor-pointer' data-action='behaviour--togglable#toggle'>Expand filter</a>
    </div>
  </div>
  <div data-behaviour--togglable-target='content' class='hidden mt-6 grid 2xl:grid-cols-4 xl:grid-cols-3 gap-4 items-end'>
    <div>
      <%= component 'form/search_input', form: f, attr: :code, placeholder: t('.search_by_codes'), label_name: t('.search_by_code_label'), options: { parent_css: 'w-72' } %>
    </div>
    <div>
      <%= component 'form/search_input', form: f, attr: :ident, placeholder: t('.search_by_idents'), label_name: t('.search_by_ident_label'), options: { parent_css: 'w-72' } %>
    </div>
    <div>
      <%= component 'form/search_input', form: f, attr: :email, placeholder: t('.search_by_emails'), label_name: t('.search_by_email_label'), options: { parent_css: 'w-72' } %>
    </div>
    <div class='w-72'>
      <%= component 'form/dropdown_input', form: f, attribute: :ident_type, enum: Contact.human_enum_options(:role), heroicon_name: 'user-circle' %>
    </div>
    <div class='w-72'>
      <%= component 'form/dropdown_input', form: f, attribute: :state, enum: Contact.human_enum_options(:state), heroicon_name: 'user-circle' %>
    </div>
    <div class='w-72'>
      <%= component 'form/country_select_input', form: f, attribute: :ident_country, heroicon_name: 'globe-alt' %>
    </div>
    <div class='w-72'>
      <%= component 'form/date_input', form: f, attribute: :updated_start_date, heroicon_name: 'user' %>
    </div>
    <div class='w-72'>
      <%= component 'form/date_input', form: f, attribute: :updated_end_date, heroicon_name: 'user' %>
    </div>
    <div class='w-72'>
      <%= component 'form/date_input', form: f, attribute: :created_start_date, heroicon_name: 'user' %>
    </div>
    <div class='w-72'>
      <%= component 'form/date_input', form: f, attribute: :created_end_date, heroicon_name: 'user' %>
    </div>
    <div class='flex flex-col justify-center'>
      <div class='w-72'>
        <%= component 'form/multiple_input', form: f, collection: Contact::STATUSES, attribute: :contact_status, placeholder: t('.contact_status'), classes: '' %>
      </div>
    </div>
    <div class='flex flex-col justify-center'>
      <%= link_to 'Clear', '#', 
          class: 'flex w-64 items-center justify-center rounded-md border border-orange-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-orange-50 self-baseline',
          data: { action: 'filter--clear-form#clearForm' } %>
    </div>
  </div>
<% end %>

app/views/registrar/contacts/edit.html.erb
<div class='flex flex-col w-full'>
  <div class="overflow-hidden bg-white shadow sm:rounded-lg">
    <div class="px-4 py-5 sm:px-6">
      <h3 class="text-lg font-medium leading-6 text-gray-900">Applicant Information</h3>
      <p class="mt-1 max-w-2xl text-sm text-gray-500">Personal details and application.</p>
    </div>
  </div>

  <div class='px-4 py-5 sm:px-6 container mx-auto rounded-md shadow-md border border-gray-300 mt-12'>
      <%= form_with model: @contact, url: registrar_contact_path(uuid: @contact.uuid), method: :put, class: 'w-full mt-8 space-y-3 flex justify-center flex-col' do |form| %>

        <%= render 'form', form: form %>

        <div class='flex justify-end'>
          <%= form.submit t('.submit'), class: 'mt-8 text-gray-600 w-64 rounded-md border border-[#A99F96] bg-white py-2 px-4 text-sm font-medium text-[#A99F96] shadow-sm hover:bg-[#A99F96] hover:text-white mt-2 cursor-pointer' %>
        </div>
      <% end %>
  </div>  
</div>  

app/views/registrar/contacts/index.html.erb
<div class="container mx-auto mt-12 px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-xl font-semibold text-gray-900"><%= t('.title') %></h1>
      <p class="mt-2 text-sm text-gray-700">A list of all the users in your account including their name, title, email and role.</p>
    </div>
    <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
      <%= link_to t('add_contact'), new_registrar_contact_path, class: "flex w-64 inline items-center justify-center rounded-md border border-indigo-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-indigo-50" %>
    </div>
  </div>

  <%= render 'filter' %>

  <%= turbo_frame_tag 'contacts' do %>
    <div class="-mx-4 mt-8 overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:-mx-6 md:mx-0 md:rounded-lg">
      <table class="min-w-full divide-y divide-gray-300">
        <thead class="bg-gray-50">
          <tr>
            <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Name</th>
            <th scope="col" class="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 lg:table-cell">Code</th>
            <th scope="col" class="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 sm:table-cell">Email</th>
            <th scope="col" class="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 sm:table-cell">State</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Domains</th>
            <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
              <span class="sr-only">Edit</span>
            </th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-200 bg-white">
          <%= render @contacts %>
        </tbody>
      </table>
    </div>

    <div class="flex justify-center">
      <% if @pagy.pages > 1 %>
        <div class="footer flex text-center mt-4">
          <%== pagy_nav(@pagy)%>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/registrar/contacts/new.html.erb
<div class='flex flex-col w-full'>
  <div class="overflow-hidden bg-white shadow sm:rounded-lg">
    <div class="px-4 py-5 sm:px-6">
      <h3 class="text-lg font-medium leading-6 text-gray-900">Applicant Information</h3>
      <p class="mt-1 max-w-2xl text-sm text-gray-500">Personal details and application.</p>
    </div>
  </div>

  <div class='px-4 py-5 sm:px-6 container mx-auto rounded-md shadow-md border border-gray-300 mt-12'>
      <%= form_with model: @contact, url: registrar_contacts_path, class: 'w-full mt-8 space-y-3 flex justify-center flex-col' do |form| %>

        <%= render 'form', form: form %>

        <div class='flex justify-end'>
          <%= form.submit t('.submit'), class: 'mt-8 text-gray-600 w-64 rounded-md border border-[#A99F96] bg-white py-2 px-4 text-sm font-medium text-[#A99F96] shadow-sm hover:bg-[#A99F96] hover:text-white mt-2 cursor-pointer' %>
        </div>
      <% end %>
  </div>  
</div>  

app/views/registrar/contacts/show.html.erb
<div class='flex flex-col w-full'>
  <div class="overflow-hidden bg-white shadow sm:rounded-lg">
    <div class="px-4 py-5 sm:px-6">
      <h3 class="text-lg font-medium leading-6 text-gray-900">Applicant Information</h3>
      <p class="mt-1 max-w-2xl text-sm text-gray-500">Personal details and application.</p>
    </div>
  </div>

  <div class="px-4 py-5 sm:px-6 container mx-auto rounded-md shadow-md border border-gray-300 mt-12">
    <%= component 'contacts/info', contact: @contact %>

    <div class='flex items-center justify-end space-x-3'>
      <%= link_to t('.edit'), edit_registrar_contact_path(uuid: @contact.uuid), class: "px-3 py-1 rounded-md text-white bg-blue-400 hover:bg-blue-500 cursor-pointer" %>

      <%= button_to t('.delete'), registrar_contact_path(uuid: @contact.uuid), method: :delete, class: "px-3 py-1 rounded-md text-white bg-red-400 hover:bg-red-500 cursor-pointer", form: { data: { turbo_confirm: t(".confirm_delete") } } %>
    </div>

    <div>
      <h2 class="text-sm font-medium text-gray-500 mb-2"><%= t('.domains') %></h2>
        <%= component 'lists/basic_list', collection: @contact.domains.uniq %>
    </div>
  </div>
</div>