config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  root 'dashboards#index'
  mount Sidekiq::Web => '/sidekiq'
  mount ActionCable.server => '/cable'

  namespace :admin do
    resource :sessions, only: %i[new create]
    resource :settings, only: %i[show update]
    resource :synchronizes, only: %i[create]
    resource :restore_services, only: %i[create]

    resources :registrar_users, param: :uuid
    resources :domain_prices, param: :uuid, except: %i[show]

    namespace :contacts do
      resource :searches, only: %i[show]
    end
  end

  resource :sessions, only: %i[new]
  delete 'logout', to: 'sessions#destroy'

  namespace :settings do
    resources :configurations, only: %i[index create]
    resources :introduces, only: %i[index]

    namespace :est_tld do
      resource :validations, only: %i[create]
    end
  end

  namespace :auth do
    match '/tara/setup', via: %i[get post], to: 'tara#setup'
    match '/tara/callback', via: %i[get post], to: 'tara#callback', as: :tara_callback
    match '/tara/cancel', via: %i[get post delete], to: 'tara#cancel',
                          as: :tara_cancel
    get '/failure', to: 'tara#cancel'
  end

  namespace :registrar do
    resources :poll_messages, only: %i[update index] do
      scope module: :poll_messages do
        resource :dequeues, only: %i[update]
      end
    end
    resources :invoices, param: :uuid
    resources :contacts, param: :uuid do
      collection do
        get :search
      end
    end
    resources :domains, param: :uuid
    resources :renews, param: :uuid, only: %i[show update]
    resource :sessions, only: %i[new create destroy]
    resource :transfers, only: %i[show update]
    resource :settings, only: %i[show update]
  end

  namespace :registrant do
    resources :domains, param: :uuid
    resource :profiles, only: %i[edit update]
    resources :pending_actions, param: :uuid, only: %i[show]

    resources :contacts, param: :uuid do
      collection do
        get :search
      end
    end

    scope module: :invoices do
      resource :pay_invoices, only: %i[create]
      match '/pay_invoices_callback', via: %i[get], to: 'pay_invoices#callback', as: :pay_invoices_callback
    end
  end
end

app/models/domain_price.rb
class DomainPrice < ApplicationRecord
  ZONES = ['ee'].freeze

  # enum operation_category: { create_domain: 0, renew_domain: 1 }
  enum operation_categories: [ :create_domain, :renew_domain ]

  # validates :price, :valid_from, :operation_category, :duration, presence: true
  # validates :operation_category, inclusion: { in: Proc.new { |price| price.class.operation_categories } }
  # validates :duration, inclusion: { in: Proc.new { |price| price.class.durations.values } },
  #                      if: :should_validate_duration?

  after_initialize do
    self.valid_from ||= Time.zone.now
  end

  # def self.operation_categories
  #   %w[create renew]
  # end

  def self.durations
    {
      '3 months' => 3.months,
      '6 months' => 6.months,
      '9 months' => 9.months,
      '1 year' => 1.year,
      '2 years' => 2.years,
      '3 years' => 3.years,
      '4 years' => 4.years,
      '5 years' => 5.years,
      '6 years' => 6.years,
      '7 years' => 7.years,
      '8 years' => 8.years,
      '9 years' => 9.years,
      '10 years' => 10.years,
    }
  end

  def months
    duration / 1.month
  end

  def years
    duration / 1.year
  end

  def self.statuses
    %w[upcoming effective expired]
  end
end

app/controllers/admin/domain_prices_controller.rb
module Admin
  class DomainPricesController < ApplicationController
    include Roles::AdminAbilitable

    def index
      @domain_prices = DomainPrice.all
    end

    def create
      # category = DomainPrice.operation_categories.keys[price_params[:operation_category].to_i]
      # price_params[:operation_category] = category if category

      @price = DomainPrice.new(price_params)
      
      if @price.save
        flash[:notice] = t('.created')
        redirect_to admin_domain_prices_path, status: :see_other
      else
        flash.now[:alert] = @price.errors.full_messages.join(', ')
        render :new, status: :unprocessable_entity
      end
    end

    def new
      @domain_price = DomainPrice.new
    end

    def edit
    end

    def update
    end

    def destroy
    end

    private

    def price_params
      params.require(:domain_price).permit(:price, :valid_from, :valid_to, :duration, :operation_category, :zone)
    end
  end
end

app/views/admin/domain_prices/_domain_price.html.erb
<tr>
  <td class="w-full max-w-0 py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:w-auto sm:max-w-none sm:pl-6">
    <%= domain_price.zone %>
    <dl class="font-normal lg:hidden">
      <dt class="sr-only"><%= domain_price.zone %></dt>
      <dd class="mt-1 truncate text-gray-700"><%= domain_price.price %></dd>
      <dt class="sr-only sm:hidden"><%= domain_price.operation_category %></dt>
      <dd class="mt-1 truncate text-gray-700"><%= domain_price.duration %></dd>
      <dt class="mt-1 truncate text-gray-700"><%= domain_price.valid_from %></dt>
      <dd class="mt-1 truncate text-gray-700"><%= domain_price.valid_to %></dd>
    </dl>
  </td>
  <td class="hidden px-3 py-4 text-sm text-gray-500 lg:table-cell"><%= domain_price.price %></td>
  
  <td class="hidden px-3 py-4 text-sm text-gray-500 lg:table-cell"><%= domain_price.operation_category %></td>
  <td class="hidden px-3 py-4 text-sm text-gray-500 sm:table-cell"><%= domain_price.duration %></td>
  <td class="hidden px-3 py-4 text-sm text-gray-500 sm:table-cell"><%= domain_price.valid_from %></td>
  <td class="hidden px-3 py-4 text-sm text-gray-500 sm:table-cell"><%= domain_price.valid_to %></td>
  <td class="py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6 flex justify-end space-x-3">
    <%= link_to t('.edit'), '#', class: "px-3 py-1 rounded-md text-white bg-blue-400 hover:bg-blue-500 cursor-pointer", target: '_top' %>

    <%= button_to t('.delete'), '#', method: :delete, class: "px-3 py-1 rounded-md text-white bg-red-400 hover:bg-red-500 cursor-pointer", form: { data: { turbo_confirm: t(".confirm_delete") } } %>
  </td>
</tr>

app/views/admin/domain_prices/_form.html.erb
<div class='flex flex-row justify-start space-x-96 items-start'>
  <div class='flex flex-col space-y-4'>

    <%= component 'divider', label: t('.general') %>

    <%= tag.div class: 'w-96' do %>
      <%= component 'form/dropdown_input', form: form, attribute: :zone, enum: options_for_select(DomainPrice::ZONES, selected: 1), heroicon_name: 'user-circle', include_blank: false %>
    <% end %>

    <%= tag.div class: 'w-96' do %>
      <%= component 'form/dropdown_input', form: form, attribute: :operation_category, enum: options_for_select(DomainPrice.operation_categories, selected: 1), heroicon_name: 'user-circle', include_blank: false %>
    <% end %>

    <%= tag.div class: 'w-96' do %>
      <%= component 'form/dropdown_input', form: form, attribute: :duration, enum: options_for_select(DomainPrice.durations, selected: 1), heroicon_name: 'user-circle', include_blank: false %>
    <% end %>

    <div class='w-96'>
      <%= component 'form/number_input', form: form, attribute: :price, heroicon_name: 'user', placeholder: '5.00' %>
    </div>

    <div class='w-96'>
      <%= component 'form/datetime_input', form: form, attribute: :valid_from, heroicon_name: 'user' %>
    </div>

    <div class='w-96'>
      <%= component 'form/datetime_input', form: form, attribute: :valid_to, heroicon_name: 'user' %>
    </div>
  </div>
</div>

app/views/admin/domain_prices/index.html.erb
<div class="container mx-auto  mt-12 px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-xl font-semibold text-gray-900"><%= t('.title') %></h1>
      <p class="mt-2 text-sm text-gray-700">A list of all the users in your account including their name, title, email and role.</p>
    </div>
    <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none flex space-x-3">
      <%#= link_to t('.transfer'), registrar_transfers_path, class: "flex w-64 inline items-center justify-center rounded-md border border-orange-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-orange-50" %>
      <%= link_to t('add_price'), new_admin_domain_price_path, class: "flex w-64 inline items-center justify-center rounded-md border border-indigo-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-indigo-50" %>
    </div>
  </div>

  <%#= render 'filter' %>

  <%= turbo_frame_tag 'domains' do %>
    <div class="-mx-4 mt-8 overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:-mx-6 md:mx-0 md:rounded-lg">
      <table class="min-w-full divide-y divide-gray-300">
        <thead class="bg-gray-50">
          <tr>
            <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Domain Zone</th>
            <th scope="col" class="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 sm:table-cell">Price</th>
            <th scope="col" class="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 lg:table-cell">Operation Category</th>
            <th scope="col" class="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 sm:table-cell">Duration</th>
            <th scope="col" class="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 lg:table-cell">Valid from</th>
            <th scope="col" class="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 sm:table-cell">Valid to</th>
            <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
              <span class="sr-only">Edit</span>
            </th>
          </tr>
        </thead>
          <tbody class="divide-y divide-gray-200 bg-white">
                <%= render @domain_prices %>
          </tbody>
      </table>
    </div>

    <div class="flex justify-center">
      <%# if @pagy.pages > 1 %>
        <div class="footer flex text-center mt-4">
          <%#== pagy_nav(@pagy)%>
        </div>
      <%# end %>
    </div>
  <% end %>
</div>

app/views/admin/domain_prices/new.html.erb
<div class='flex flex-col w-full'>
  <div class="overflow-hidden bg-white shadow sm:rounded-lg">
    <div class="px-4 py-5 sm:px-6">
      <h3 class="text-lg font-medium leading-6 text-gray-900">Applicant Information</h3>
      <p class="mt-1 max-w-2xl text-sm text-gray-500">Personal details and application.</p>
    </div>
  </div>

  <div class='px-4 py-5 sm:px-6 container mx-auto rounded-md shadow-md border border-gray-300 mt-12'>
    <%= form_with model: @domain_price, url: admin_domain_prices_path, class: 'w-full mt-8 space-y-3 flex justify-center flex-col' do |form| %>

      <%= render 'form', form: form %>

      <div class='flex justify-end'>
        <%= form.submit t('.submit'), class: 'mt-8 text-gray-600 w-64 rounded-md border border-[#A99F96] bg-white py-2 px-4 text-sm font-medium text-[#A99F96] shadow-sm hover:bg-[#A99F96] hover:text-white mt-2 cursor-pointer' %>
      </div>
    <% end %>
  </div>  
</div>  