config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  root 'dashboards#index'
  mount Sidekiq::Web => '/sidekiq'
  mount ActionCable.server => '/cable'

  namespace :admin do
    resource :sessions, only: %i[new create]
    resource :settings, only: %i[show update]
    resource :synchronizes, only: %i[create]
    resource :restore_services, only: %i[create]

    resources :registrar_users, param: :uuid
    resources :domain_prices, param: :uuid, except: %i[show]

    namespace :contacts do
      resource :searches, only: %i[show]
    end
  end

  resource :sessions, only: %i[new]
  delete 'logout', to: 'sessions#destroy'

  namespace :settings do
    resources :configurations, only: %i[index create]
    resources :introduces, only: %i[index]

    namespace :est_tld do
      resource :validations, only: %i[create]
    end
  end

  namespace :auth do
    match '/tara/setup', via: %i[get post], to: 'tara#setup'
    match '/tara/callback', via: %i[get post], to: 'tara#callback', as: :tara_callback
    match '/tara/cancel', via: %i[get post delete], to: 'tara#cancel',
                          as: :tara_cancel
    get '/failure', to: 'tara#cancel'
  end

  namespace :registrar do
    resources :poll_messages, only: %i[update index] do
      scope module: :poll_messages do
        resource :dequeues, only: %i[update]
      end
    end
    resources :invoices, param: :uuid
    resources :contacts, param: :uuid do
      collection do
        get :search
      end
    end
    resources :domains, param: :uuid
    resources :renews, param: :uuid, only: %i[show update]
    resource :sessions, only: %i[new create destroy]
    resource :transfers, only: %i[show update]
    resource :settings, only: %i[show update]
  end

  namespace :registrant do
    resources :domains, param: :uuid
    resource :profiles, only: %i[edit update]
    resources :pending_actions, param: :uuid, only: %i[show]

    resources :contacts, param: :uuid do
      collection do
        get :search
      end
    end

    scope module: :invoices do
      resource :pay_invoices, only: %i[create]
      match '/pay_invoices_callback', via: %i[get], to: 'pay_invoices#callback', as: :pay_invoices_callback
    end
  end
end

app/controllers/registrant/domains_controller.rb
module Registrant
  class DomainsController < ApplicationController
    include Roles::RegistrantAbilitable

    def new
      @domain = Domain.new

      Tld::Estonian::MIN_DOMAIN_CONTACT_COUNT.times do |i|
        admin_contact = Contact.find_by(code: current_user.code, role: :priv)
        tech_contact = Contact.find_by(code: Setting.code_of_technical_contact || current_user.code)

        if i % 2 == 0
          @domain.admin_domain_contacts.build(contact: admin_contact)
        else
          @domain.tech_domain_contacts.build(contact: tech_contact)
        end

      end

      Tld::Estonian::MIN_NAMESERVER_COUNT.times do |i|
        next if Setting.default_nameserver_records[i].blank?

        current_nameserver = JSON.parse(Setting.default_nameserver_records[i])
        @domain.nameservers.build(
          hostname: current_nameserver['hostname'],
          ipv4: current_nameserver['ipv4'],
          ipv6: current_nameserver['ipv6']
        )
      end

      @domain.dnssec_keys.build(
        flags: Setting.dnssec_default_value['flags'],
        protocol: Setting.dnssec_default_value['protocol'],
        algorithm: Setting.dnssec_default_value['algorithm'],
        public_key: Setting.dnssec_default_value['public_key']
      )
    end

    def index
      pending_actions = current_user.pending_actions.order(created_at: :desc)
      @pagy, @pending_actions = pagy(pending_actions, items: 10, link_extra: 'data-turbo-action="advance"')

      if current_user.domains.present?
        @pagy_domain, @domains = pagy(current_user.domains.order(created_at: :desc), items: 10, link_extra: 'data-turbo-action="advance"')
      else
        @pagy_domain, @domains = pagy(Domain.none, items: 10, link_extra: 'data-turbo-action="advance"')
      end
    end

    def show; end

    def edit; end

    def create
      # TODO: Need to add validation for ident of contacts, email and other attributes

      unless DomainPrice.all.any?
        flash.now[:alert] = t('.no_domain_prices')

        render turbo_stream: [
          turbo_stream.append('flash', partial: 'layouts/flash')
        ]

        return
      end

      domain_price = DomainPrice.find(domain_params[:domain_price])

      pending = PendingAction.create(
        user: current_user,
        action: :domain_create,
        status: :pending,
        info: domain_params.to_h.merge(
          period: domain_price.months,
          domain_price: domain_price.attributes
        )
      )

      @invoice = pending.create_invoice_by_pending_action(domain_price.price.to_f)

      if @invoice
        flash[:notice] = t('.success')

        redirect_to registrant_domains_path, status: :see_other

        # render turbo_stream: [
        #   turbo_stream.append('flash', partial: 'layouts/flash'),
        #   turbo_stream.append('payment_method', partial: 'registrant/domains/payment_form',
        #                                        locals: { invoice: @invoice})
        # ]
      else
        flash[:alert] = @invoice.errors.full_messages
        render turbo_stream: turbo_stream.replace('flash', partial: 'layouts/flash')
      end
    end

    def update; end

    def destroy; end

    private

    def domain_params
      params.require(:domain).permit(
        :name, 
        :period, 
        :reserved_pw, 
        :domain_price,
        tech_domain_contacts_attributes: [
          :id, 
          :_destroy, 
          contact: [:role, :name, :email, :ident, :country_code, :_destroy, :phone, :phone_code, :state, :street, :city, :zip, :address_country_code]
        ],
        admin_domain_contacts_attributes: [
          :id, 
          :_destroy, 
          contact: [:role, :name, :email, :ident, :_destroy, :country_code, :phone, :phone_code, :state, :street, :city, :zip, :address_country_code]
        ],
        nameservers_attributes: [
          :id,
          :hostname,
          :ipv4,
          :ipv6,
          :_destroy
        ],
        dnssec_keys_attributes: [
          :id,
          :flags,
          :protocol,
          :algorithm,
          :public_key,
          :_destroy
        ]
      )
    end
  end
end

app/controllers/registrar/contacts_controller.rb
module Registrar
  class ContactsController < ApplicationController
    include Roles::RegistrarAbilitable

    before_action :load_contact, only: %i[edit update destroy show]

    def index
      @pagy, @contacts = pagy(Contact.search_filter(params).distinct, items: 15, link_extra: 'data-turbo-action="advance"')
    end

    def new
      @contact = Contact.new
    end

    def show; end

    def create
      @contact = Contact.new(contact_params)

      if @contact.save
        redirect_to registrar_contacts_path, status: :see_other, notice: t('.success')
      else
        flash[:alert] = @contact.errors.full_messages.join(', ')
        render 'registrar/contacts/new', status: :unprocessable_entity
      end
    end

    def update
      if @contact.update(contact_params)
        redirect_to registrar_contacts_path, status: :see_other, notice: t('.success')
      else
        flash[:alert] = @contact.errors.full_messages.join(', ')
        render 'registrar/contacts/edit', status: :unprocessable_entity
      end
    end

    def destroy
      if @contact.destroy
        redirect_to registrar_contacts_path, status: :see_other, notice: t('.success')
      else
        Rails.logger.info @contact.errors.inspect
        flash[:alert] = @contact.errors.full_messages.join(', ')
        render 'registrar/contacts/index', status: :unprocessable_entity
      end
    end

    def search
      puts '----'
      puts params[:query]
      puts '-----'

      @contacts = Contact.search(params[:query])

      puts '==== contacts'
      puts @contacts.inspect
      puts '====='

      render json: @contacts.limit(5).map(&:as_json)
    end

    private

    def load_contact
      @contact = Contact.find_by(uuid: params[:uuid])
    end

    def contact_params
      params.require(:contact).permit(:code, :country_code, :ident, :phone_code,
                                      :role, :name, :email, :phone, :address_country_code,
                                      :city, :street, :state, :zip, :legal_document)
    end
  end
end

app/controllers/registrar/domains_controller.rb
module Registrar
  class DomainsController < ApplicationController
    include Roles::RegistrarAbilitable

    before_action :load_domain, only: %i[show edit update destroy]

    def index
      @pagy, @domains = pagy(Domain.search(params).distinct, items: 15, link_extra: 'data-turbo-action="advance"')
    end

    def new
      @domain = Domain.new
      Tld::Estonian::MIN_NAMESERVER_COUNT.times do
        @domain.nameservers.build
      end
      Tld::Estonian::MIN_DOMAIN_CONTACT_COUNT.times do |i|
        i % 2 == 0 ? @domain.domain_contacts.build(type: 'AdminDomainContact') : @domain.domain_contacts.build(type: 'TechDomainContact')
      end

      @domain.dnssec_keys.build
    end

    def create
      domain_params_modified = domain_params.except(:period)
      @domain = Domain.new(domain_params_modified)
      period = params[:domain][:period].to_i
      @domain.expire_at = calculate_expiry(period)

      if @domain.save
        redirect_to registrar_domains_path, status: :see_other, notice: t('.success')
      else
        Rails.logger.info @domain.errors.inspect
        flash[:alert] = @domain.errors.full_messages.join(', ')
        render :new, status: :unprocessable_entity
      end
    end

    def show; end

    def edit; end

    def update
      domain_params_modified = domain_params.except(:period)
      period = params[:domain][:period].to_i
      domain_params_modified[:expire_at] = calculate_expiry(period)

      if @domain.update(domain_params_modified)
        redirect_to registrar_domains_path, status: :see_other, notice: t('.success')
      else
        Rails.logger.info @domain.errors.inspect
        flash[:alert] = @domain.errors.full_messages.join(', ')
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      if @domain.destroy
        redirect_to registrar_domains_path, status: :see_other, notice: t('.success')
      else
        Rails.logger.info @domain.errors.inspect
        flash[:alert] = @domain.errors.full_messages.join(', ')
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def load_domain
      @domain = Domain.find_by(uuid: params[:uuid])
    end

    def calculate_expiry(period)
      (Time.zone.now.advance(months: period) + 1.day).beginning_of_day
    end

    def domain_params
      params.require(:domain).permit(:name, :registrant_id, :period, :reserved_pw,
                                     domain_contacts_attributes: %i[id contact_id type _destroy],
                                     nameservers_attributes: %i[id hostname ipv4 ipv6 _destroy],
                                     dnssec_keys_attributes: %i[id flags protocol algorithm public_key _destroy])
    end
  end
end

app/controllers/registrar/invoices_controller.rb
module Registrar
  class InvoicesController < ApplicationController
    include Roles::RegistrarAbilitable

    before_action :load_invoice, only: %i[show edit update destroy]

    def index
      @pagy, @invoices = pagy(Invoice.all.order(created_at: :desc), items: 15, link_extra: 'data-turbo-action="advance"')
    end

    def show; end

    def new
      @invoice = Invoice.new
      @invoice.invoice_items.build
    end

    def create
      @invoice = Invoice.new(invoice_params)

      if @invoice.save
        redirect_to registrar_invoices_path, status: :see_other, notice: t('.success')
      else
        Rails.logger.info @invoice.errors.inspect
        flash[:alert] = @invoice.errors.full_messages.join(', ')
        render :new, status: :unprocessable_entity
      end
    end

    def edit; end

    def update
      if @invoice.update(invoice_params)
        redirect_to registrar_invoices_path, status: :see_other, notice: t('.success')
      else
        Rails.logger.info @invoice.errors.inspect
        flash[:alert] = @invoice.errors.full_messages.join(', ')
        render :edit, status: :unprocessable_entit
      end
    end

    def destroy
      if @invoice.destroy
        redirect_to registrar_invoices_path, status: :see_other, notice: t('.success')
      else
        Rails.logger.info @invoice.errors.inspect
        flash[:alert] = @invoice.errors.full_messages.join(', ')
        render :index, status: :unprocessable_entit
      end
    end

    private

    def load_invoice
      @invoice = Invoice.find_by(uuid: params[:uuid])
    end

    def invoice_params
      params.require(:invoice).permit(:buyer_id, :name, :country_code, :state, :street, :city, :zip, :phone, :url, :status,
                                      :email, :description, :invoice_items_attributes => [:id, :unit_price, :quantity, :description, :_destroy] )
    end
  end
end

app/controllers/registrar/poll_messages/dequeues_controller.rb
module Registrar
  module PollMessages
    class DequeuesController < ApplicationController
      # rubocop:disable Metrics/AbcSize
      # rubocop:disable Metrics/MethodLength
      def update
        result = EstonianTld::PollMessageService.new(tld:).mark_as_read(params[:poll_message_id])

        if result.success

          data = EstonianTld::SummaryService.call(tld: @tld)
          struct_data = EstonianTld::SummarySerializer.call(dirty: data)
          @notification = struct_data[:notification]
          @notifications_count = struct_data[:notifications_count]

          flash.now[:notice] = t('.success')
          render turbo_stream: [
            turbo_stream.append('flash', partial: 'layouts/flash'),

            # TODO: This is not working. Need to fix animation playing before execute another turbo actions.
            # turbo_stream.poll_message_dequeue('message-box', element_id: 'message-box'),

            turbo_stream.update('notification-header',
                                html: "#{t('dashboards.notifications.notification_title')} (#{@notifications_count})"),
            if @notification
              turbo_stream.append('dashboard-notification', partial: 'dashboards/notifications/message',
                                                            locals: { notification: @notification })
            else
              turbo_stream.append('dashboard-notification', partial: 'dashboards/notifications/no_message')
            end
          ]
        else
          flash[:alert] = t('.failure')
          render turbo_stream: [
            turbo_stream.append('flash', partial: 'layouts/flash')
          ]
        end
      end
    end
  end
end

app/controllers/registrar/poll_messages_controller.rb
module Registrar
  class PollMessagesController < ApplicationController
    include Roles::RegistrarAbilitable
    before_action :notifications

    def index; end

    # rubocop:disable Metrics/AbcSize
    # rubocop:disable Metrics/MethodLength
    def update
      result = EstonianTld::PollMessageService.new(tld:).mark_as_read(params[:id])

      if result.success
        flash.now[:notice] = t('.success')
        render turbo_stream: [
          turbo_stream.append('flash', partial: 'layouts/flash'),
          turbo_stream.poll_message_mark_as_read("poll_message_#{params[:id]}", item_id: params[:id]),
          turbo_stream.append('poll_messages', partial: 'registrar/poll_messages/poll_message',
                                               locals: { poll_message: @poll_messages.last })
        ]
      else
        flash[:alert] = t('.failure')
        render turbo_stream: [
          turbo_stream.append('flash', partial: 'layouts/flash')
        ]
        # render 'dashboards/index', status: :unprocessable_entity
      end
    end

    def notifications
      all_notifications = EstonianTld::PollMessageService.new(tld: @tld).all_notifications

      puts '----'
      puts all_notifications.body['data']
      puts '----'

      @all_notifications = if all_notifications.body['data'].blank?
                             []
                           else
                             EstonianTld::NotificationSerializer.call(body: all_notifications.body['data'])
                           end

      @pagy, @poll_messages = pagy_array(@all_notifications, items: 15, link_extra: 'data-turbo-action="advance"')
    end
  end
end

app/controllers/registrar/renews_controller.rb
module Registrar
  class RenewsController < ApplicationController
    include Roles::RegistrarAbilitable

    def show
      @domain = Domain.find_by_uuid(params[:uuid])
    end

    # rubocop:disable Metrics/AbcSize
    # rubocop:disable Metrics/MethodLength
    def update
      @domain = Domain.find_by_uuid(params[:uuid])

      result = EstonianTld::RenewService.new(tld: Tld.first).transfer(
        payload: renew_params, domain_name: @domain.name
      )

      if result.success
        @domain.renew(period_in_months: renew_params[:period].to_i)
        redirect_to registrar_domains_path, notice: t('.success'), status: :see_other
      else
        Rails.logger.info "Error: #{result.body['message']}"
        flash.now[:alert] = "Error: #{result.body['message']}"

        render turbo_stream: turbo_stream.replace('flash', partial: 'layouts/flash')
      end
    end

    private

    def renew_params
      params.require(:domain).permit(:name, :period, :expire_at)
    end
  end
end

app/helpers/registrars/contacts_helper.rb
module Registrars
  module ContactsHelper
    def show_address?
      Setting.show_address_customer
    end
  end
end

app/views/registrar/domains/_domain.html.erb
<tr>
  <td class="w-full max-w-0 py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:w-auto sm:max-w-none sm:pl-6">
    <%= domain.name %>
    <dl class="font-normal lg:hidden">
      <dt class="sr-only"><%= domain.name %></dt>
      <dd class="mt-1 truncate text-gray-700"><%= domain.registrant.name %></dd>
      <dt class="sr-only sm:hidden"><%= domain.expire_at %></dt>
    </dl>
  </td>
  <td class="hidden px-3 py-4 text-sm text-gray-500 lg:table-cell"><%= domain.registrant.name %></td>
  <td class="hidden px-3 py-4 text-sm text-gray-500 lg:table-cell">
    <span class="py-1 px-4 rounded-3xl text-white <%= domain.active? ? 'bg-green-500' : 'bg-gray-500' %>"><%= domain.state %></span>
  </td>
  <td class="hidden px-3 py-4 text-sm text-gray-500 sm:table-cell"><%= domain.expire_at %></td>
  <td class="py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6 flex justify-end space-x-3">
    <%= link_to t('.renew'), registrar_renews_path(uuid: domain.uuid), class: "px-3 py-1 rounded-md text-white bg-green-400 hover:bg-green-500 cursor-pointer", target: '_top' %>

    <%= link_to t('.show'), registrar_domain_path(uuid: domain.uuid), class: "px-3 py-1 rounded-md text-white bg-yellow-400 hover:bg-yellow-500 cursor-pointer", target: '_top' %>

    <%= link_to t('.edit'), edit_registrar_domain_path(uuid: domain.uuid), class: "px-3 py-1 rounded-md text-white bg-blue-400 hover:bg-blue-500 cursor-pointer", target: '_top' %>

    <%= button_to t('.delete'), registrar_domain_path(uuid: domain.uuid), method: :delete, class: "px-3 py-1 rounded-md text-white bg-red-400 hover:bg-red-500 cursor-pointer", form: { data: { turbo_confirm: t(".confirm_delete") } } %>
  </td>
</tr>

app/views/registrar/domains/index.html.erb
<div class="container mx-auto  mt-12 px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-xl font-semibold text-gray-900"><%= t('.title') %></h1>
      <p class="mt-2 text-sm text-gray-700">A list of all the users in your account including their name, title, email and role.</p>
    </div>
    <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none flex space-x-3">
      <%= link_to t('.transfer'), registrar_transfers_path, class: "flex w-64 inline items-center justify-center rounded-md border border-orange-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-orange-50" %>
      <%= link_to t('add_domain'), new_registrar_domain_path, class: "flex w-64 inline items-center justify-center rounded-md border border-indigo-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-indigo-50" %>
    </div>
  </div>

  <%= render 'filter' %>

  <%= turbo_frame_tag 'domains' do %>
    <div class="-mx-4 mt-8 overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:-mx-6 md:mx-0 md:rounded-lg">
      <table class="min-w-full divide-y divide-gray-300">
        <thead class="bg-gray-50">
          <tr>
            <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Domain Name</th>
            <th scope="col" class="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 lg:table-cell">Registrant name</th>
            <th scope="col" class="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 lg:table-cell">State</th>
            <th scope="col" class="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 sm:table-cell">Expire Date</th>
            <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
              <span class="sr-only">Edit</span>
            </th>
          </tr>
        </thead>
          <tbody class="divide-y divide-gray-200 bg-white">
                <%= render @domains %>
          </tbody>
      </table>
    </div>

    <div class="flex justify-center">
      <% if @pagy.pages > 1 %>
        <div class="footer flex text-center mt-4">
          <%== pagy_nav(@pagy)%>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/registrar/domains/show.html.erb
<div class='flex flex-col w-full mb-6'>
  <div class="overflow-hidden bg-white shadow sm:rounded-lg">
    <div class="px-4 py-5 sm:px-6">
      <h3 class="text-lg font-medium leading-6 text-gray-900">Applicant Information</h3>
      <p class="mt-1 max-w-2xl text-sm text-gray-500">Personal details and application.</p>
    </div>
  </div>

  <div class="px-4 py-5 sm:px-6 container mx-auto rounded-md shadow-md border border-gray-300 mt-12">
    <dl class="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-2">
      <div class="sm:col-span-1">
        <dt class="text-sm font-medium text-gray-500"><%= t('.name') %></dt>
        <dd class="mt-1 text-sm text-gray-900"><%= @domain.name %></dd>
      </div>
      <div class="sm:col-span-1">
        <dt class="text-sm font-medium text-gray-500"><%= t('.transfer_code') %></dt>
        <dd class="mt-1 text-sm text-gray-900"><%= @domain.information['transfer_code'] %></dd>
      </div>
      <div class="sm:col-span-1">
        <dt class="text-sm font-medium text-gray-500"><%= t('.registrant_name ') %></dt>
        <dd class="mt-1 text-sm text-gray-900"><%= @domain.registrant.name  %></dd>
      </div>
      <div class="sm:col-span-1">
        <dt class="text-sm font-medium text-gray-500"><%= t('.registered_at')%></dt>
        <% if @domain.registry_created_at.present? %>
          <dd class="mt-1 text-sm text-gray-900"><%= l(@domain.registry_created_at.to_datetime) %></dd>
        <% else %>
          <dd class="mt-1 text-sm text-red-500"><%= t('.need_to_synchronize') %></dd>
        <% end %>
      </div>
      <div class="sm:col-span-1">
        <dt class="text-sm font-medium text-gray-500"><%= t('.valid_to')%></dt>
        <dd class="mt-1 text-sm text-gray-900"><%= l(@domain.expire_at) %></dd>
      </div>
      <div class="sm:col-span-1">
        <dt class="text-sm font-medium text-gray-500"><%= t('.created_at')%></dt>
        <dd class="mt-1 text-sm text-gray-900"><%= l(@domain.created_at) %></dd>
      </div>
      <div class="sm:col-span-1">
        <dt class="text-sm font-medium text-gray-500"><%= t('.updated_at')%></dt>
        <dd class="mt-1 text-sm text-gray-900"><%= l(@domain.updated_at) %></dd>
      </div>
      <div class="sm:col-span-1">
        <dt class="text-sm font-medium text-gray-500"><%= t('.state')%></dt>
        <dd class="mt-1">
          <span class="py-1 px-4 rounded-3xl text-white <%= @domain.active? ? 'bg-green-500' : 'bg-gray-500' %>"><%= @domain.state %></span>
        </dd>
      </div>

      <%= component 'common/statuses_info', status_notes: @domain.status_notes, statuses: @domain.statuses %>
      
      <div class="sm:col-span-2">
      <h2 class="text-sm font-medium text-gray-500 mb-2"><%= t('.domain_contacts') %></h2>
        <%= component 'lists/basic_list', collection: @domain.contacts.uniq %>
      </div>

      <div class="sm:col-span-2">
        <div class="mt-8 border-t border-gray-200 pt-8">
          <h2 class="text-sm font-medium text-gray-500 mb-2"><%= t('.nameservers') %></h2>

          <div class="prose prose-sm mt-4 text-gray-500">

            <% if @domain.nameservers.blank? %>
              <div class='flex flex-col justify-content items-center p-10 full-w'>
                <p class='font-3xl mb-3'><%= t('.no_nameservers') %></p>
              </div>
            <% else %>
              <ul role="list" class='flex space-x-3'>
                <% @domain.nameservers.each do |nameserver| %>
                  <li>
                    <p><%= nameserver.hostname %></p>
                    <p><%= nameserver.ipv4 %></p>
                    <p><%= nameserver.ipv6 %></p>
                  </li>
                <% end %>
              </ul>
            <% end %>
          </div>
        </div>
      </div>

      <div class="sm:col-span-2">
        <div class="mt-8 border-t border-gray-200 pt-8">
          <h2 class="text-sm font-medium text-gray-500 mb-2"><%= t('.dnskey') %></h2>

          <div class="prose prose-sm mt-4 text-gray-500">
            <% if @domain.dnssec_keys.blank? %>
              <div class='flex flex-col justify-content items-center p-10 full-w'>
                <p class='font-3xl mb-3'><%= t('.no_dnskey') %></p>
              </div>
            <% else %>
              <ul role="list" class='flex space-x-3'>
                <% @domain.dnssec_keys.each do |dns| %>
                  <li>
                    <p><%= dns.flags %></p>
                    <p><%= dns.protocol %></p>
                    <p><%= dns.algorithm %></p>
                    <p><%= dns.public_key %></p>
                  </li>
                <% end %>
              </ul>
            <% end %>
          </div>
        </div>
      </div>
    </dl>

    <hr>

    <div class='flex items-center justify-end space-x-3 mt-8 mb-8'>
      <%= link_to t('.renew'), registrar_renews_path(uuid: @domain.uuid), class: "px-3 py-1 rounded-md text-white bg-green-400 hover:bg-green-500 cursor-pointer" %>

      <%= link_to t('.edit'), edit_registrar_domain_path(uuid: @domain.uuid), class: "px-3 py-1 rounded-md text-white bg-blue-400 hover:bg-blue-500 cursor-pointer" %>

      <%= button_to t('.delete'), registrar_domain_path(uuid: @domain.uuid), method: :delete, class: "px-3 py-1 rounded-md text-white bg-red-400 hover:bg-red-500 cursor-pointer", form: { data: { turbo_confirm: t(".confirm_delete") } } %>
    </div>
  </div>
</div>