config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  root 'dashboards#index'
  mount Sidekiq::Web => '/sidekiq'
  mount ActionCable.server => '/cable'

  namespace :admin do
    resource :sessions, only: %i[new create]
    resource :settings, only: %i[show update]
    resource :synchronizes, only: %i[create]
    resource :restore_services, only: %i[create]

    resources :registrar_users, param: :uuid
    resources :domain_prices, param: :uuid, except: %i[show]

    namespace :contacts do
      resource :searches, only: %i[show]
    end
  end

  resource :sessions, only: %i[new]
  delete 'logout', to: 'sessions#destroy'

  namespace :settings do
    resources :configurations, only: %i[index create]
    resources :introduces, only: %i[index]

    namespace :est_tld do
      resource :validations, only: %i[create]
    end
  end

  namespace :auth do
    match '/tara/setup', via: %i[get post], to: 'tara#setup'
    match '/tara/callback', via: %i[get post], to: 'tara#callback', as: :tara_callback
    match '/tara/cancel', via: %i[get post delete], to: 'tara#cancel',
                          as: :tara_cancel
    get '/failure', to: 'tara#cancel'
  end

  namespace :registrar do
    resources :poll_messages, only: %i[update index] do
      scope module: :poll_messages do
        resource :dequeues, only: %i[update]
      end
    end
    resources :invoices, param: :uuid
    resources :contacts, param: :uuid do
      collection do
        get :search
      end
    end
    resources :domains, param: :uuid
    resources :renews, param: :uuid, only: %i[show update]
    resource :sessions, only: %i[new create destroy]
    resource :transfers, only: %i[show update]
    resource :settings, only: %i[show update]
  end

  namespace :registrant do
    resources :domains, param: :uuid
    resource :profiles, only: %i[edit update]
    resources :pending_actions, param: :uuid, only: %i[show]

    resources :contacts, param: :uuid do
      collection do
        get :search
      end
    end

    scope module: :invoices do
      resource :pay_invoices, only: %i[create]
      match '/pay_invoices_callback', via: %i[get], to: 'pay_invoices#callback', as: :pay_invoices_callback
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @tld = Tld.first

    if current_user&.class&.name == 'RegistrarUser'
      data = EstonianTld::SummaryService.call(tld: @tld)
      struct_data = EstonianTld::SummarySerializer.call(dirty: data)

      @notification = struct_data[:notification]
      @notifications_count = struct_data[:notifications_count]
      @username = struct_data[:username]
      @balance = struct_data[:balance]
      @registry_domains_count = struct_data[:domains_count]
      @domains_count = Domain.count
      @contacts_count = struct_data[:contacts_count]
      @last_login_date = struct_data[:last_login_date]
    elsif current_user&.class&.name == 'User'
      contact = Contact.find_by(ident: current_user.code)
      @domains = contact&.domains
    end
  end
end

app/views/dashboards/notifications/_message.html.erb
<div id='message-box' data-controller='behaviour--animation-end'>
  <div>
  <div class='my-6 flex justify-center'>
    <%= button_to 'Dequeue', registrar_poll_message_dequeues_path(poll_message_id: notification.id), method: :patch, class: 'flex w-64 items-center justify-center rounded-md border border-blue-300 bg-white px-4 py-2 text-sm font-medium text-blue-700 shadow-sm hover:bg-blue-50' %>
  </div>

  <div class="mt-6 flow-root shadow-xl p-10 mx-auto w-1/2 border bg-blue-100">

    <p><span class='font-bold'>Message #</span> <%= notification.id %></p>
    <p><span class='font-bold'>Text</span> <%= notification.text %></p>
    <p><span class='font-bold'>Queued at </span> <%= l notification.created_at.to_datetime %></p>

  </div>

  <div class="flex justify-center mt-10 mb-5">
    <%= link_to t('.view_all'), registrar_poll_messages_path, class: 'flex w-64 items-center justify-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50' %>
  </div>
  </div>
</div>

app/views/dashboards/notifications/_no_message.html.erb
<div class='w-full flex justify-center p-12 border mt-12'>
  <h2 class='font-bold text-[16px]'>No notifications</h2>
</div>